#!/bin/bash

set -euo pipefail

shopt -s failglob

. "${PROFILE_DIR}"/bin/sh/shell_fns --source-only

app_name="${MACHINE} ${ARCH}"

install_messages "start" "${app_name}"

case "${MACHINE}" in
    *Mac*)
        echo "Mac install instructions here"

        case "${ARCH}" in
            *aarch64*)
                echo "aarch64 architecture specific install instructions here";;
            *arm64*)
                echo "arm64 architecture specific install instructions here";;
            *)
            echo "Generic install instructions here";;
        esac
        ;;
esac

install_messages "start" "${app_name}"
