---
language: ruby
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - ree
  - jruby-18mode
  - jruby-19mode
  - jruby-head
branches:
  only:
    - master
notifications:
  recipients:
  - caizhaoff@gmail.com
before_script:
- gem install hoe-travis --no-rdoc --no-ri
after_script:
script: rake spec
